Gui kit
GennadiyBakulin/Sber-School_JavaScript pull request #2
Opened 2022-08-22 14:59 UTC by GennadiyBakulin

Добрый день Джабраил!
Прошу проверить мою работу по созданию макета Админ панели на html и css из курса Сбершкола Javascript.
Не могу понять почему, но моя работа некорректно отображается в githab pages (склоняюсь к тому что githab pages некорректно работает с большой вложенностью файлов и папок).
В связи с этим к гитхабу привязал свой домен (gennadiy-bakulin.ru) и выложил проект на него (ссылка внизу).

https://gennadiy-bakulin.ru/

2022-08-23 23:33 UTC, Muslik requested changes
Очень круто сделали презентацию вашей работы. За это респект.
Есть замечания касательно некоторых БЭМ именований.
Замечания касательно работы dropdown-a.

Плюс я к сожалению не смог посмотреть ваши выносы в папки в рамках PR. Пришлось клонить ветку. В целом с точки зрения БЭМ подход правильный. Но я считаю это избыточным. Достаточно просто иметь файл .button в котором описаны стили для блока с кнопкой. Плюс у вас во многих файлах .important что не очень хорошо.

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +            <button class="button button_size-medium button_text-black button_padding-medium">
Это radio

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +        <button class="button button_bg-color-blue button_size-medium button_text-white button_padding-medium">
```.button_bg-color-blue и .button_text-white``` проще объединить в один класс:
```.button_theme_blue``` Потому что завтра для синей кнопки добавится border-radius другой и вам придется заводить новый класс.

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +        <button class="button button_bg-color-blue button_size-medium button_text-white button_padding-medium">
Не очень красиво когда у вас в названии класс css свойства. Я бы этот padding зашил бы в размер кнопки.
А в случае когда у кнопки только иконка без текста и нужен отдельный padding, сделал бы отдельный модификатор: ```.button_icon-only``` например

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +            <span class="button__icon-container">
Не нужен контейнер. Можете сразу все стили для svg указывать

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +                <svg class="icon icon_color-theme-light-blue" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
Тему иконка возьмет выше из кнопки:
```
.button_theme_blue .button__icon {}
```
Не нужен отдельный класс

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +            <div class="input__title">Дата и время заказа</div>
Это должен быть label для инпута

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +        <div class="input input_empty">
Что значит модификатор input_empty. Для чего он? Зашейте дефолтные стили в класс .input. Не нужен отдельный модификатор.
Будет три состояния - дефолтный, ошибка, disabled

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +                <input class="input__field-center" type="text" placeholder="Введите">
input должен быть disabled

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +                <span class="input__field-left"></span>
Зачем пустой тег

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +                <span class="input__field-left"></span>
Зачем пустой тег

2022-08-23 23:33 UTC, Muslik commented on gui-light-theme.html
> +                <span class="input__field-right">
Не нужны три секции. Просто задайте блоку padding справа и все. Кнопка с крестиком и иконка с замочком будут absolut-ом расположены справа

2022-08-24 10:12 UTC, Muslik requested changes
upd

2022-08-30 12:44 UTC, GennadiyBakulin commented on gui-light-theme.html
> +                <span class="input__field-right">
согласен, действительно оптимальный вариант. Исправлю

2022-08-30 12:47 UTC, GennadiyBakulin commented on gui-light-theme.html
> +                <span class="input__field-left"></span>
Этот тег я сделал для того чтобы в панели администратора добавлять префиксы в блоке где выбор фильтров идет по дате и суммам - с, по, от, до.
Думаю если захочется поменять цвет или размер шрифта пригодиться.

2022-08-30 12:47 UTC, GennadiyBakulin commented on gui-light-theme.html
> +                <span class="input__field-left"></span>
Этот тег я сделал для того чтобы в панели администратора добавлять префиксы в блоке где выбор фильтров идет по дате и суммам - с, по, от, до.
Думаю если захочется поменять цвет или размер шрифта пригодиться.

2022-08-30 12:48 UTC, GennadiyBakulin commented on gui-light-theme.html
> +        <div class="input input_empty">
согласен, исправлю.

2022-08-30 12:49 UTC, GennadiyBakulin commented on gui-light-theme.html
> +            <span class="button__icon-container">
Согласен

2022-09-03 05:09 UTC, GennadiyBakulin commented on gui-light-theme.html
> +            <button class="button button_size-medium button_text-black button_padding-medium">
Переделал на Radio плюсом скорректировал сам элемент Radio

2022-09-03 05:33 UTC, GennadiyBakulin commented on gui-light-theme.html
> +            <div class="input__title">Дата и время заказа</div>
Исправил

2022-09-03 07:36 UTC, GennadiyBakulin commented on gui-light-theme.html
> +                <input class="input__field-center" type="text" placeholder="Введите">
Не понял замечания, но Input по всем ошибкам скорректировал.

2022-09-03 15:11 UTC, GennadiyBakulin commented on gui-light-theme.html
> +        <button class="button button_bg-color-blue button_size-medium button_text-white button_padding-medium">
Исправил

2022-09-03 15:11 UTC, GennadiyBakulin commented on gui-light-theme.html
> +            <span class="button__icon-container">
Удалил контейнер

2022-09-03 15:13 UTC, GennadiyBakulin commented on gui-light-theme.html
> +                <svg class="icon icon_color-theme-light-blue" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
Не изменял, так как по проекту в однотипных кнопках могут присутствовать svg иконки с разными цветовыми оформлениями.

2022-09-03 15:14 UTC, GennadiyBakulin commented
Добрый вечер Джабраил!
Работу над ошибками провел.

2022-09-04 14:27 UTC, Muslik requested changes
https://www.youtube.com/watch?v=LI1uuvY8G4I

2022-09-05 13:26 UTC, GennadyBakulin commented
Добрый вечер Джабраил!
Исправил указанные в видео недочеты.

https://gennadiybakulin.github.io/Sber-School_JavaScript/

2022-09-11 15:52 UTC, Muslik approved these changes

2022-09-15 15:30 UTC, closed without merging

2022-09-15 15:31 UTC, GennadiyBakulin commented
Одобрено ревьювером